### ISSUE TITLE
Weapon minigun (special)

### ISSUE THREAD

**Issue by Kaysoro** [Kaysoro/Santarminator#1]
- [x] Délai d'attente d'une seconde (le temps de chauffer le moteur)
- [x] Tir en cône avec réutilisation de bullet
- [x] Sprite 1 Santa
- [x] Sprite 2 Tir
- [x] Sound 1 (préchauffe moteur)
- [x] Sound 2 (tir en cône)
Temps d'utilisation à fixer (10s de base ?)
Dégât à fixer (> pistolet)

**Comment by AscalonThisWay** [comment]
Sprite à trouver
