### ISSUE TITLE
Split entities.js

### ISSUE THREAD

**Issue by Kaysoro** [Kaysoro/Santarminator#10]
Découper entities comme suit : 
- [x] weapons.js : Armes classiques/spéciales
- [x] deco.js  : Décoration en tout genre
- [x] pickups.js : Pick-ups
- [x] santa.js : Santa
- [x] generator.js : Pour les générateurs lol
- [x] enemies.js : Pour les enemies

**Comment by AscalonThisWay** [comment]
J'ai viré entities.js et j'ai ajouté un utils.js dans /js/lib/ pour foutre les méthodes en vrac
