### ISSUE TITLE
Weapon pompe (basic)

### ISSUE THREAD

**Issue by AscalonThisWay** [Kaysoro/Santarminator#4]
- [x] Tir en cône, portée courte
- [x] Temps d'utilisation infini
- [x] Dégât de base élevé (15-20 ?)
- [x] Rechargement après X tirs ?
- [x] Sprite 1 Santa
- [x] Sprite 2 Tir
- [x] Sound 1 (préchauffe moteur)
- [x] Sound 2 (rechargement)

**Comment by Kaysoro** [comment]
Ajout d'une spécificité : 
[ ] Rechargement de l'arme au bout de 8 cartouches

**Comment by Kaysoro** [comment]
Les dégâts sont très forts au càc, puis réduisent fortement avec le temps (on passe de 50 à 5 en une seconde).
Idem, la vitesse décroît jusqu'à être nulle après une seconde.

**Comment by Kaysoro** [comment]
Les tirs sont effectués en spray, avec un rad plus ou moins random (on est sur un shotgun quoi, bat les couilles de la précision, on pète tout)
